spring:
  datasource:
    url: jdbc:h2:mem:whoisspy
    driverClassName: org.h2.Driver
    username: idolice
    password:

  jpa:
      hibernate:
        ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp

server:
  port: 8086