version: 2
jobs:
  build:
    machine:
      java:
        version: oraclejdk8

    working_directory: ~/whoisspy

    steps:

      - checkout

      - run: ./gradlew clean build

      - store_artifacts:
          path: build

  deploy:
    machine: true
    working_directory: ./build
    steps:
      - run:
          name: Display whole list
          command: ls -al

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: set-ci
