version: 2
jobs:
  build:
    machine:
      java:
        version: oraclejdk8

    working_directory: ~/whoisspy

    steps:

      - checkout

      - run: ./gradlew clean build

      - store_artifacts:
          path: build/libs/whoisspy-0.0.1-SNAPSHOT.jar

  deploy:
    machine: true
    working_directory: ./build
    steps:
      - run:
          name: Display whole list
          command: ls -al ../

      - run:
          name: Display current position
          command: pwd

      - run:
          name: Display those variables
          command: env

      - run:
          name: Download jar file
          command: |

            export CIRCLE_TOKEN='?circle-token=93106a0b530273d9cb344ea608bc609490fdf202'

            curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts$CIRCLE_TOKEN | grep -o 'https://[^"]*' > artifacts.txt

            <artifacts.txt xargs -P4 -I % wget %$CIRCLE_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: set-ci
