version: 2
jobs:
  build:
    machine:
      java:
        version: oraclejdk8

    working_directory: ~/whoisspy

    steps:

      - checkout

      - run: ./gradlew clean build

      - run: ./gradlew jar

      - store_artifacts:
          path: ./build/libs/who-is-spy-0.0.1-SNAPSHOT.jar

